spring.application.name=Enotes_API_service

spring.datasource.url =jdbc:mysql://localhost:3306/enotes_db
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=none